# Generated by Django 5.0.2 on 2024-03-03 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mileapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
