# Generated by Django 5.0.2 on 2024-04-10 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mileapp', '0005_brand_is_active_category_is_blocked_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productattribute',
            name='old_price',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='productattribute',
            name='stock',
            field=models.IntegerField(),
        ),
    ]
