# Generated by Django 5.0.2 on 2024-04-06 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_wallet_wallethistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='address',
            field=models.TextField(max_length=200),
        ),
    ]
