# Generated by Django 5.0.2 on 2024-04-08 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_alter_address_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='address',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='cartorder',
            name='selected_address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
