# Generated by Django 5.0.2 on 2024-04-09 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminhome', '0002_productoffer_categoryoffer'),
        ('payment', '0006_alter_cartitem_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartorder',
            name='coupen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adminhome.coupon'),
        ),
    ]
