# Generated by Django 5.0.2 on 2024-04-10 06:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminhome', '0002_productoffer_categoryoffer'),
        ('payment', '0007_alter_cartorder_coupen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adminhome.coupon'),
        ),
    ]
