# Generated by Django 5.0.2 on 2024-04-17 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminhome', '0002_productoffer_categoryoffer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productoffer',
            name='discount_percentage',
            field=models.IntegerField(),
        ),
    ]
